import { PrismaClient } from '@prisma/client';
import { CommonStatus } from '../../src/shared/constants/common-status.constant';

const prisma = new PrismaClient();

export async function seedConfigs() {
  console.log('🌱 开始创建可配置数据...');

  const configsData = [
    // ====================== UI 默认配置 ======================
    {
      key: 'uiDefaults.theme',
      value: 'light',
      name: '默认主题',
      description: '系统默认主题，可被用户覆盖',
      type: 'string',
      group: 'uiDefaults',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: '界面主题配置',
    },
    {
      key: 'uiDefaults.language',
      value: 'zh-CN',
      name: '默认语言',
      description: '系统默认语言，可被用户覆盖',
      type: 'string',
      group: 'uiDefaults',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: '界面语言配置',
    },
    {
      key: 'uiDefaults.timezone',
      value: 'Asia/Shanghai',
      name: '默认时区',
      description: '系统默认时区，可被用户覆盖',
      type: 'string',
      group: 'uiDefaults',
      status: CommonStatus.ENABLED,
      sort: 2,
      remark: '系统时间配置',
    },
    {
      key: 'uiDefaults.sidebarCollapsed',
      value: 'false',
      name: '侧边栏折叠',
      description: '系统默认侧边栏折叠状态',
      type: 'boolean',
      group: 'uiDefaults',
      status: CommonStatus.ENABLED,
      sort: 3,
      remark: '界面布局配置',
    },
    {
      key: 'uiDefaults.pageSize',
      value: '10',
      name: '表格默认分页',
      description: '表格列表默认每页显示条数',
      type: 'number',
      group: 'uiDefaults',
      status: CommonStatus.ENABLED,
      sort: 4,
      remark: '界面偏好配置',
    },
    {
      key: 'uiDefaults.welcomeMessage',
      value: '这是你的系统运行概览，祝你工作愉快',
      name: '系统欢迎语',
      description: '首页欢迎用户显示文字，管理员可改',
      type: 'string',
      group: 'uiDefaults',
      status: CommonStatus.ENABLED,
      sort: 5,
      remark: '首页欢迎配置',
    },
    {
      key: 'uiDefaults.showBreadcrumb',
      value: 'true',
      name: '显示面包屑',
      description: '是否显示页面面包屑导航',
      type: 'boolean',
      group: 'uiDefaults',
      status: CommonStatus.ENABLED,
      sort: 6,
      remark: '界面布局配置',
    },

    // ====================== 安全策略 ======================
    {
      key: 'securityPolicy.watermark.enabled',
      value: 'true',
      name: '水印开关',
      description: '是否显示水印',
      type: 'boolean',
      group: 'securityPolicy',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: '安全策略配置',
    },
    {
      key: 'securityPolicy.password.minLength',
      value: '6',
      name: '密码最小长度',
      description: '用户密码的最小长度要求',
      type: 'number',
      group: 'securityPolicy',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: '密码策略配置',
    },
    {
      key: 'securityPolicy.password.requireComplexity',
      value: 'true',
      name: '密码复杂度要求',
      description: '密码必须包含字母+数字+特殊字符',
      type: 'boolean',
      group: 'securityPolicy',
      status: CommonStatus.ENABLED,
      sort: 2,
      remark: '密码策略配置',
    },
    {
      key: 'securityPolicy.login.failureLockCount',
      value: '5',
      name: '登录失败锁定次数',
      description: '连续登录失败次数锁定账号',
      type: 'number',
      group: 'securityPolicy',
      status: CommonStatus.ENABLED,
      sort: 3,
      remark: '登录策略配置',
    },

    // ====================== 功能开关 ======================
    {
      key: 'features.fileUpload.maxSize',
      value: '10485760',
      name: '文件上传最大大小',
      description: '文件上传最大限制（字节）',
      type: 'number',
      group: 'features',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: '文件管理配置',
    },
    {
      key: 'features.fileUpload.allowedTypes',
      value: 'jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx',
      name: '允许上传的文件类型',
      description: '允许上传的文件类型列表',
      type: 'string',
      group: 'features',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: '文件类型限制',
    },
    {
      key: 'features.oss.enabled',
      value: 'false',
      name: '对象存储启用',
      description: '是否启用 OSS 上传',
      type: 'boolean',
      group: 'features',
      status: CommonStatus.ENABLED,
      sort: 2,
      remark: '对象存储配置',
    },
    {
      key: 'features.email.enabled',
      value: 'false',
      name: '邮件功能启用',
      description: '是否启用邮件功能',
      type: 'boolean',
      group: 'features',
      status: CommonStatus.ENABLED,
      sort: 3,
      remark: '邮件功能配置',
    },
    {
      key: 'features.notification.settings',
      value: '{"email": true, "sms": false, "push": true}',
      name: '通知设置',
      description: '系统通知设置',
      type: 'json',
      group: 'features',
      status: CommonStatus.ENABLED,
      sort: 4,
      remark: '通知功能配置',
    },
    {
      key: 'features.oauth.github.enabled',
      value: 'false',
      name: 'GitHub登录',
      description: '是否启用 GitHub OAuth 登录',
      type: 'boolean',
      group: 'features',
      status: CommonStatus.ENABLED,
      sort: 5,
      remark: '第三方登录配置',
    },

    // ====================== 用户默认值 ======================
    {
      key: 'user.default.password',
      value: '123456',
      name: '默认密码',
      description: '新用户的默认密码',
      type: 'string',
      group: 'user',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: '用户管理默认值',
    },
    {
      key: 'user.avatar.default',
      value: 'https://api.dicebear.com/9.x/bottts/svg?seed=GavinRay',
      name: '默认头像',
      description: '新用户或未上传头像的默认头像',
      type: 'string',
      group: 'user',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: '用户头像默认配置',
    },
  ];

  for (const configData of configsData) {
    await prisma.config.upsert({
      where: { key: configData.key },
      update: configData,
      create: configData,
    });
  }

  console.log('✅ 配置数据创建完成');
}
