import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedConfigs() {
  console.log('🌱 开始创建配置数据...');

  const configsData = [
    // ====================== 系统配置 ======================
    {
      key: 'system.name',
      value: 'Nest Admin',
      name: '系统名称',
      description: '系统显示名称',
      type: 'string',
      group: 'system',
      status: 1,
      sort: 0,
      remark: '系统基础配置',
    },
    {
      key: 'system.version',
      value: '1.0.0',
      name: '系统版本',
      description: '系统版本号',
      type: 'string',
      group: 'system',
      status: 1,
      sort: 1,
      remark: '系统版本信息',
    },
    {
      key: 'system.description',
      value: '基于NestJS的管理后台系统',
      name: '系统描述',
      description: '系统描述信息',
      type: 'string',
      group: 'system',
      status: 1,
      sort: 2,
      remark: '系统描述配置',
    },
    {
      key: 'system.logo',
      value: '/static/logo.png',
      name: '系统Logo',
      description: '系统顶部Logo显示',
      type: 'string',
      group: 'system',
      status: 1,
      sort: 3,
      remark: '界面基础配置',
    },
    {
      key: 'system.favicon',
      value: '/static/favicon.ico',
      name: '系统Favicon',
      description: '浏览器标签图标',
      type: 'string',
      group: 'system',
      status: 1,
      sort: 4,
      remark: '界面基础配置',
    },
    {
      key: 'system.theme.default',
      value: 'blue',
      name: '默认主题色',
      description: '系统默认主题色，可被用户覆盖',
      type: 'string',
      group: 'system',
      status: 1,
      sort: 5,
      remark: '界面主题配置',
    },
    {
      key: 'system.language.default',
      value: 'zh-CN',
      name: '默认语言',
      description: '系统默认语言',
      type: 'string',
      group: 'system',
      status: 1,
      sort: 6,
      remark: '界面语言配置',
    },
    {
      key: 'system.timezone.default',
      value: 'Asia/Shanghai',
      name: '默认时区',
      description: '系统默认时区',
      type: 'string',
      group: 'system',
      status: 1,
      sort: 7,
      remark: '系统时间配置',
    },
    {
      key: 'system.welcome.message',
      value: '欢迎使用 Nest Admin',
      name: '系统欢迎语',
      description: '首页欢迎用户显示文字',
      type: 'string',
      group: 'system',
      status: 1,
      sort: 8,
      remark: '首页欢迎配置',
    },
    {
      key: 'system.layout.sidebarCollapsed',
      value: 'false',
      name: '侧边栏折叠',
      description: '系统默认侧边栏折叠状态',
      type: 'boolean',
      group: 'system',
      status: 1,
      sort: 9,
      remark: '界面布局配置',
    },
    {
      key: 'system.layout.pageSize',
      value: '20',
      name: '表格默认分页',
      description: '表格列表默认每页显示条数',
      type: 'number',
      group: 'system',
      status: 1,
      sort: 10,
      remark: '界面偏好配置',
    },

    // ====================== 用户配置 ======================
    {
      key: 'user.default.password',
      value: 'admin123',
      name: '默认密码',
      description: '新用户的默认密码',
      type: 'string',
      group: 'user',
      status: 1,
      sort: 0,
      remark: '用户管理配置',
    },
    {
      key: 'user.password.minLength',
      value: '6',
      name: '密码最小长度',
      description: '用户密码的最小长度要求',
      type: 'number',
      group: 'user',
      status: 1,
      sort: 1,
      remark: '密码策略配置',
    },
    {
      key: 'user.password.requireComplexity',
      value: 'true',
      name: '密码复杂度要求',
      description: '密码必须包含字母+数字+特殊字符',
      type: 'boolean',
      group: 'user',
      status: 1,
      sort: 2,
      remark: '密码策略配置',
    },
    {
      key: 'user.session.timeout',
      value: '7200',
      name: '会话超时时间',
      description: '用户会话超时时间（秒）',
      type: 'number',
      group: 'user',
      status: 1,
      sort: 3,
      remark: '会话管理配置',
    },
    {
      key: 'user.login.failureLockCount',
      value: '5',
      name: '登录失败锁定次数',
      description: '连续登录失败次数锁定账号',
      type: 'number',
      group: 'user',
      status: 1,
      sort: 4,
      remark: '安全配置',
    },
    {
      key: 'user.mfa.enabled',
      value: 'false',
      name: '多因素认证',
      description: '是否启用多因素认证',
      type: 'boolean',
      group: 'user',
      status: 1,
      sort: 5,
      remark: '安全配置',
    },
    {
      key: 'user.avatar.default',
      value: '/static/avatar-default.png',
      name: '默认头像',
      description: '新用户或未上传头像的默认头像',
      type: 'string',
      group: 'user',
      status: 1,
      sort: 6,
      remark: '用户头像默认配置',
    },

    // ====================== 文件/存储配置 ======================
    {
      key: 'file.upload.maxSize',
      value: '10485760',
      name: '文件上传最大大小',
      description: '文件上传的最大大小限制（字节）',
      type: 'number',
      group: 'storage',
      status: 1,
      sort: 0,
      remark: '文件管理配置',
    },
    {
      key: 'file.upload.allowedTypes',
      value: 'jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx',
      name: '允许上传的文件类型',
      description: '允许上传的文件类型列表',
      type: 'string',
      group: 'storage',
      status: 1,
      sort: 1,
      remark: '文件类型限制',
    },
    {
      key: 'storage.local.path',
      value: '/uploads',
      name: '本地上传路径',
      description: '文件上传到本地的目录',
      type: 'string',
      group: 'storage',
      status: 1,
      sort: 2,
      remark: '本地存储配置',
    },
    {
      key: 'storage.oss.enabled',
      value: 'false',
      name: 'OSS上传启用',
      description: '是否启用对象存储上传',
      type: 'boolean',
      group: 'storage',
      status: 1,
      sort: 3,
      remark: '对象存储配置',
    },

    // ====================== 邮件/通知配置 ======================
    {
      key: 'email.enabled',
      value: 'false',
      name: '邮件功能启用',
      description: '是否启用邮件功能',
      type: 'boolean',
      group: 'notify',
      status: 1,
      sort: 0,
      remark: '邮件功能配置',
    },
    {
      key: 'email.smtp.host',
      value: 'smtp.example.com',
      name: 'SMTP服务器地址',
      description: 'SMTP服务器主机地址',
      type: 'string',
      group: 'notify',
      status: 1,
      sort: 1,
      remark: 'SMTP配置',
    },
    {
      key: 'email.smtp.port',
      value: '587',
      name: 'SMTP端口',
      description: 'SMTP服务器端口',
      type: 'number',
      group: 'notify',
      status: 1,
      sort: 2,
      remark: 'SMTP端口配置',
    },
    {
      key: 'email.smtp.username',
      value: '',
      name: 'SMTP用户名',
      description: 'SMTP登录用户名',
      type: 'string',
      group: 'notify',
      status: 1,
      sort: 3,
      remark: 'SMTP配置',
    },
    {
      key: 'email.smtp.password',
      value: '',
      name: 'SMTP密码',
      description: 'SMTP登录密码',
      type: 'string',
      group: 'notify',
      status: 1,
      sort: 4,
      remark: 'SMTP配置',
    },
    {
      key: 'notification.settings',
      value: '{"email": true, "sms": false, "push": true}',
      name: '通知设置',
      description: '系统通知设置',
      type: 'json',
      group: 'notify',
      status: 1,
      sort: 5,
      remark: '通知功能配置',
    },

    // ====================== 第三方 OAuth 配置 ======================
    {
      key: 'oauth.github.enabled',
      value: 'false',
      name: 'GitHub登录',
      description: '是否启用GitHub OAuth登录',
      type: 'boolean',
      group: 'auth',
      status: 1,
      sort: 0,
      remark: '第三方登录配置',
    },
    {
      key: 'oauth.github.clientId',
      value: '',
      name: 'GitHub Client ID',
      description: 'GitHub OAuth Client ID',
      type: 'string',
      group: 'auth',
      status: 1,
      sort: 1,
      remark: '第三方登录配置',
    },
    {
      key: 'oauth.github.clientSecret',
      value: '',
      name: 'GitHub Client Secret',
      description: 'GitHub OAuth Client Secret',
      type: 'string',
      group: 'auth',
      status: 1,
      sort: 2,
      remark: '第三方登录配置',
    },
  ];

  for (const configData of configsData) {
    await prisma.config.upsert({
      where: { key: configData.key },
      update: configData,
      create: configData,
    });
  }

  console.log('✅ 配置数据创建完成');
}
